### ISSUE TITLE
File mode specification error: (void-function sfz-mode)

### ISSUE THREAD

**Issue by condecarlos** [sfztools/emacs-sfz-mode#1]
Greetings... I'm getting this when opening every sfz file and the mode is not working at all. Installed from MELPA repository. I don't know how to get more information about this problem. Please let me know if there is a solution. Thanks in advance.

**Comment by jpcima** [comment]
Hi. Somehow I missed this notification when issue was opened some months ago, sorry about that.
Let me know if the PR helps to fix the problem.
